Railsでユーザーフォローを作る
bimadisiwin/book-app pull request #7
Opened 2020-11-17 02:23 UTC by bimadisiwin

Railsでユーザーフォロー機能を実装しました。

2020-11-20 04:30 UTC, komagata requested changes

2020-11-20 04:30 UTC, komagata commented on app/assets/stylesheets/relationships.scss
> +// Place all the styles related to the relationships controller here.
不要なファイルは削除しちゃってください〜

2020-11-20 04:30 UTC, komagata commented on app/helpers/relationships_helper.rb
> +module RelationshipsHelper
不要なファイルは削除しちゃってください

2020-11-20 08:55 UTC, komagata requested changes

2020-11-20 08:55 UTC, komagata commented on test/controllers/relationships_controller_test.rb
> +# frozen_string_literal: true
不要なテストも削除してください。

そのPRで不要なファイルは追加しないようにしてください。特にgenerateされたファイルは一つ一つ何の意味があって作られたのか、不要なのかどうか調べてaddするようにしてください。仕事のレビューでよく指摘される点になります。

2020-11-20 09:53 UTC, bimadisiwin commented on test/controllers/relationships_controller_test.rb
> +# frozen_string_literal: true
判断に迷ったのですが、以降の自動テストのプラクティスで、使いそうなテストのファイルは残しました。この場合、削除して、テストを実装する際に、生成するという方法をとるのが正解でしょうか？

2020-11-22 05:04 UTC, komagata commented on test/controllers/relationships_controller_test.rb
> +# frozen_string_literal: true
以降で必要でも実行されない・きちんと実装されていないテストやfixtureがリポジトリに入るのはよくないです。

仕事のレビューでも同じ指摘を受けると思います。

2020-11-22 05:06 UTC, komagata commented
> Remove test file
> Remove test files

これらは意味が同じなので一つのコミットにまとめた方がいいと思います。コミットの粒度はよくレビューで指摘される点になります。
また、`Add: `などのprefixがつく場合とそうでないコミットが混在しているのでどちらかに統一した方がいいと思います。

2020-11-23 05:47 UTC, komagata commented
> Merge branch 'follow_user' of github.com:bimadisiwin/book-app into fo… …

マージコミットができてしまっているようです。
rebaseを使っていればこういうコミットはできないので修正してみてください〜

2020-11-23 07:19 UTC, bimadisiwin commented
rebaseを行ったつもりだったのですが、うまくいっていなかったようです🙇‍♂️
マージコミットを取り消して、再度プッシュをしました。

2020-11-23 11:26 UTC, komagata requested changes

2020-11-23 11:26 UTC, komagata commented on app/controllers/users_controller.rb
> +  def followings
[Railsでユーザーフォローを作る \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/170)にある[DHHはどのようにRailsのコントローラを書くのか \| POSTD](https://postd.cc/how-dhh-organizes-his-rails-controllers/)を参考にして、ControllerはCRUD以外ない形に整理してみてください。

2020-11-24 08:31 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-24 09:02 UTC, merged